[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BE_insta_clone"
version = "0.1.0"
description = "BE_insta_clone"
dependencies = [
    "Django",
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["BE_insta_clone"]